#!/usr/bin/env bash
# setup-agent-autoupdate.sh
#
# 一键安装 Agent 自动更新功能
# One-click setup for Agent auto-update feature
#
# 用法: curl -sSL https://raw.githubusercontent.com/podcctv/iperf3-test-tools/main/setup-agent-autoupdate.sh | sudo bash
#
# 或者手动执行:
# sudo bash setup-agent-autoupdate.sh
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ==============================================================================
# Configuration
# ==============================================================================
SCRIPT_VERSION="1.0.0"
REPO_URL="https://github.com/podcctv/iperf3-test-tools.git"
REPO_DIR="${REPO_DIR:-/opt/iperf3-test-tools}"
WATCHDOG_SCRIPT="/usr/local/bin/iperf-agent-watchdog.sh"
CRON_FILE="/etc/cron.d/iperf-agent-watchdog"
DATA_DIR="${AGENT_DATA_DIR:-/var/lib/iperf-agent/data}"
LOG_FILE="/var/log/iperf-agent-watchdog.log"
CONFIG_FILE="/etc/iperf-agent-watchdog.conf"

# ==============================================================================
# Pre-flight checks
# ==============================================================================
check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log_error "This script must be run as root. Use: sudo $0"
        exit 1
    fi
}

check_dependencies() {
    local missing=()
    
    for cmd in docker git curl; do
        if ! command -v "$cmd" &> /dev/null; then
            missing+=("$cmd")
        fi
    done
    
    if [ ${#missing[@]} -gt 0 ]; then
        log_error "Missing required commands: ${missing[*]}"
        log_info "Please install them first:"
        log_info "  apt-get update && apt-get install -y ${missing[*]}"
        exit 1
    fi
    
    log_success "All dependencies found"
}

# ==============================================================================
# Installation
# ==============================================================================
setup_directories() {
    log_info "Creating directories..."
    
    mkdir -p "$DATA_DIR"
    mkdir -p "$(dirname "$LOG_FILE")"
    mkdir -p "$(dirname "$REPO_DIR")"
    
    log_success "Directories created"
}

clone_or_update_repo() {
    log_info "Setting up repository..."
    
    if [ -d "$REPO_DIR/.git" ]; then
        log_info "Repository exists, updating..."
        git -C "$REPO_DIR" pull origin main 2>&1 || {
            log_warn "Git pull failed, using existing version"
        }
    else
        log_info "Cloning repository..."
        git clone --depth 1 "$REPO_URL" "$REPO_DIR"
    fi
    
    log_success "Repository ready: $REPO_DIR"
}

install_watchdog_script() {
    log_info "Installing watchdog script..."
    
    local src_script="$REPO_DIR/agent-watchdog.sh"
    
    if [ ! -f "$src_script" ]; then
        log_error "Watchdog script not found: $src_script"
        exit 1
    fi
    
    cp "$src_script" "$WATCHDOG_SCRIPT"
    chmod +x "$WATCHDOG_SCRIPT"
    
    log_success "Watchdog installed: $WATCHDOG_SCRIPT"
}

create_config_file() {
    log_info "Creating configuration file..."
    
    # Try to detect existing agent container
    local container_name=""
    local iperf_port="62001"
    
    # Look for common agent container names
    for name in iperf-agent iperf3-agent agent; do
        if docker ps -a --format '{{.Names}}' | grep -q "^${name}$"; then
            container_name="$name"
            break
        fi
    done
    
    if [ -z "$container_name" ]; then
        # Try to find any container with iperf3
        container_name=$(docker ps --format '{{.Names}}' | head -1 || echo "iperf-agent")
    fi
    
    cat > "$CONFIG_FILE" << EOF
# iperf-agent-watchdog configuration
# Generated by setup-agent-autoupdate.sh on $(date)

# Data directory (must match container's /app/data mount)
AGENT_DATA_DIR="$DATA_DIR"

# Container name to update
AGENT_CONTAINER_NAME="${container_name:-iperf-agent}"

# Default image name (used for local builds)
AGENT_IMAGE="iperf-agent:latest"

# Repository directory for local builds
REPO_DIR="$REPO_DIR"
EOF
    
    log_success "Config created: $CONFIG_FILE"
    log_info "  Container: ${container_name:-iperf-agent}"
    log_info "  Data dir: $DATA_DIR"
}

setup_cron() {
    log_info "Setting up cron job (hourly)..."
    
    cat > "$CRON_FILE" << 'EOF'
# iperf-agent-watchdog - Auto-update check
# Runs every hour to check for update requests
0 * * * * root /usr/local/bin/iperf-agent-watchdog.sh >> /var/log/iperf-agent-watchdog.log 2>&1
EOF
    
    chmod 644 "$CRON_FILE"
    
    # Ensure cron is running
    if command -v systemctl &> /dev/null; then
        systemctl restart cron 2>/dev/null || systemctl restart crond 2>/dev/null || true
    fi
    
    log_success "Cron job installed: $CRON_FILE"
}

update_container_volume() {
    log_info "Checking container data volume mount..."
    
    # Load config
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi
    
    local container="${AGENT_CONTAINER_NAME:-iperf-agent}"
    
    # Check if container exists and has the correct mount
    if docker ps -a --format '{{.Names}}' | grep -q "^${container}$"; then
        local mounts
        mounts=$(docker inspect "$container" --format '{{range .Mounts}}{{.Destination}}:{{.Source}} {{end}}' 2>/dev/null || echo "")
        
        if echo "$mounts" | grep -q "/app/data"; then
            log_success "Container '$container' already has /app/data mounted"
        else
            log_warn "Container '$container' does NOT have /app/data mounted!"
            log_warn "Auto-update will NOT work until you recreate the container with:"
            log_info ""
            log_info "  docker stop $container"
            log_info "  docker rm $container"
            log_info "  docker run -d --name $container \\"
            log_info "    -v $DATA_DIR:/app/data \\"
            log_info "    ... (other options) ..."
            log_info ""
        fi
    else
        log_warn "No container named '$container' found"
        log_info "When you create the agent container, make sure to add:"
        log_info "  -v $DATA_DIR:/app/data"
    fi
}

# ==============================================================================
# Main
# ==============================================================================
print_banner() {
    echo ""
    echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║     iperf3 Agent Auto-Update Setup Script v${SCRIPT_VERSION}            ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_summary() {
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  ✅ Installation Complete!${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "📁 Files installed:"
    echo "   • Watchdog script: $WATCHDOG_SCRIPT"
    echo "   • Config file: $CONFIG_FILE"
    echo "   • Cron job: $CRON_FILE"
    echo "   • Data directory: $DATA_DIR"
    echo "   • Log file: $LOG_FILE"
    echo ""
    echo "🔧 How it works:"
    echo "   1. Master notifies agent of available updates"
    echo "   2. Agent writes update request to $DATA_DIR/update_request.json"
    echo "   3. Watchdog (runs every minute) detects request and executes update"
    echo ""
    echo "📋 Important:"
    echo "   Make sure your agent container has this volume mount:"
    echo "   -v $DATA_DIR:/app/data"
    echo ""
    echo "🔍 Monitor logs:"
    echo "   tail -f $LOG_FILE"
    echo ""
    echo "🧪 Test watchdog manually:"
    echo "   sudo $WATCHDOG_SCRIPT"
    echo ""
}

main() {
    print_banner
    
    check_root
    check_dependencies
    
    setup_directories
    clone_or_update_repo
    install_watchdog_script
    create_config_file
    setup_cron
    update_container_volume
    
    print_summary
}

main "$@"
